### ISSUE TITLE
tp > 1 时的问题

### ISSUE THREAD

**Issue by yfzhou3993** [alibaba/Pai-Megatron-Patch#399]
你好：
        我在参考 `examples/qwen2_5/README.md` 的教程对 Qwen2.5-Coder 进行预训练的时候遇到了 tp 大于1会出现的问题，请问通常是什么原因引起的呢，非常感谢

- 使用的镜像
        dsw-registry.cn-wulanchabu.cr.aliyuncs.com/pai/pai-megatron-patch:24.07
- 显卡
A800 * 40G * 8
- 模型转换脚本
```bash
bash hf2mcore_qwen2.5_convertor.sh \
0.5B \
/checkpoint/qwen2.5-coder-0.5b/huggingface/qwen2.5-coder-0.5b \
/checkpoint/qwen2.5-coder-0.5b/megatron/qwen2.5-coder-0.5b-tp2 \
2  \
1  \
bf16 \
true \
false
```
- 训练脚本
```bash
sh run_mcore_qwen.sh  \
dsw  \
0.5B   \
1    \
4 \
1e-5   \
1e-6   \
128  \
128  \
bf16  \
2   \
1  \
1 \
true \
true   \
false \
false \
full   \
static \
100000  \
/mnt/qwen-datasets/wudao_qwenbpe_text_document   \
/mnt/qwen-datasets/wudao_qwenbpe_text_document   \
/checkpoint/qwen2.5-coder-0.5b/megatron/qwen2.5-coder-0.5b-tp2/  \
10000  \
100   \
/checkpoint/qwen2.5-coder-0.5b/megatron/20241217-try
```
- 报错信息
```
[rank6]: Traceback (most recent call last):
[rank6]:   File "/workspace/project/Pai-Megatron-Patch/examples/qwen2_5/../qwen2/pretrain_qwen.py", line 279, in <module>
[rank6]:     pretrain(
[rank6]:   File "/workspace/project/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/training.py", line 223, in pretrain
[rank6]:     initialize_megatron(
[rank6]:   File "/workspace/project/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/initialize.py", line 105, in initialize_megatron
[rank6]:     _initialize_tp_communicators()
[rank6]:   File "/workspace/project/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/initialize.py", line 211, in _initialize_tp_communicators
[rank6]:     te_module.base.initialize_ub(shape = input_shape, tp_size = args.tensor_model_parallel_size,
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/base.py", line 91, in initialize_ub
[rank6]:     if not tex.device_supports_multicast():
[rank6]: RuntimeError: /tmp/pip-req-build-9h0okhm9/transformer_engine/pytorch/csrc/extensions/../comm_gemm_overlap.h:45 in function device_supports_multicast: CUDA Error: invalid argument
...
```

**Comment by divisionblur** [comment]
似乎把脚本里关于通信和计算重叠那个参数关掉就行，我之前好像是这样。

**Comment by lostkevin** [comment]
麻烦提供一下镜像内以及宿主机的CUDA & Driver版本，谢谢。看了下报错发生在TE的这个函数
```
bool supports_multicast(int device_id) {
#if CUDART_VERSION >= 12010
  // NOTE: This needs to be guarded at compile time because the
  //       CU_DEVICE_ATTRIBUTE_MULTICAST_SUPPORTED enum is not defined in earlier CUDA versions.
  static std::vector<bool> cache(num_devices(), false);
  static std::vector<std::once_flag> flags(num_devices());
  if (device_id < 0) {
    device_id = current_device();
  }
  NVTE_CHECK(0 <= device_id && device_id < num_devices(), "invalid CUDA device ID");
  auto init = [&]() {
    CUdevice cudev;
    NVTE_CALL_CHECK_CUDA_DRIVER(cuDeviceGet, &cudev, device_id);
    int result;
    NVTE_CALL_CHECK_CUDA_DRIVER(cuDeviceGetAttribute, &result,
                                CU_DEVICE_ATTRIBUTE_MULTICAST_SUPPORTED, cudev);
    cache[device_id] = static_cast<bool>(result);
  };
  std::call_once(flags[device_id], init);
  return cache[device_id];
#else
  return false;
#endif
}


```

**Comment by yfzhou3993** [comment]
> 似乎把脚本里关于通信和计算重叠那个参数关掉就行，我之前好像是这样。

谢谢^^

是的，我尝试了下，取消 `--tp-comm-overlap` ，可以避开这个问题

**Comment by yfzhou3993** [comment]
> 麻烦提供一下镜像内以及宿主机的CUDA & Driver版本，谢谢。看了下报错发生在TE的这个函数
> 
> ```
> bool supports_multicast(int device_id) {
> #if CUDART_VERSION >= 12010
>   // NOTE: This needs to be guarded at compile time because the
>   //       CU_DEVICE_ATTRIBUTE_MULTICAST_SUPPORTED enum is not defined in earlier CUDA versions.
>   static std::vector<bool> cache(num_devices(), false);
>   static std::vector<std::once_flag> flags(num_devices());
>   if (device_id < 0) {
>     device_id = current_device();
>   }
>   NVTE_CHECK(0 <= device_id && device_id < num_devices(), "invalid CUDA device ID");
>   auto init = [&]() {
>     CUdevice cudev;
>     NVTE_CALL_CHECK_CUDA_DRIVER(cuDeviceGet, &cudev, device_id);
>     int result;
>     NVTE_CALL_CHECK_CUDA_DRIVER(cuDeviceGetAttribute, &result,
>                                 CU_DEVICE_ATTRIBUTE_MULTICAST_SUPPORTED, cudev);
>     cache[device_id] = static_cast<bool>(result);
>   };
>   std::call_once(flags[device_id], init);
>   return cache[device_id];
> #else
>   return false;
> #endif
> }
> ```

谢谢^^

宿主机环境
```bash
$ nvidia-smi
NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0
```

镜像环境
```bash
$ nvidia-smi
NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```

非常感谢！

**Comment by yfzhou3993** [comment]
谢谢！

是的，我升级了宿主机的显卡驱动后，问题解决了。

**Comment by haorannlp** [comment]
@yfzhou3993 可以问下你的torch, cuda，以及transformer engine版本吗

**Comment by yfzhou3993** [comment]
torch、cuda和te都是使用的官方镜像的原本的版本。

镜像使用的是 `dsw-registry.cn-wulanchabu.cr.aliyuncs.com/pai/pai-megatron-patch:24.07`

**Comment by QianguoS** [comment]
请问这个镜像升级多少版本成功的呢？

**Comment by yfzhou3993** [comment]
> 请问这个驱动版本升级多少版本成功的呢？

我升级到了 555.42.02

**Comment by Lynnzake** [comment]
> > 请问这个驱动版本升级多少版本成功的呢？
> 
> 我升级到了 555.42.02

@yfzhou3993 老哥，请问你这个有关tp-comm-overlap吗？还是说只要升级了cuda版本就可以了

**Comment by yfzhou3993** [comment]
> > > 请问这个驱动版本升级多少版本成功的呢？
> > 
> > 
> > 我升级到了 555.42.02
> 
> [@yfzhou3993](https://github.com/yfzhou3993) 老哥，请问你这个有关tp-comm-overlap吗？还是说只要升级了cuda版本就可以了

与tp-comm-overlap无关
只需要升级显卡驱动到能支持镜像中的CUDA的版本，就没问题了

**Comment by Lynnzake** [comment]
> > > > 请问这个驱动版本升级多少版本成功的呢？
> > > 
> > > 
> > > 我升级到了 555.42.02
> > 
> > 
> > [@yfzhou3993](https://github.com/yfzhou3993) 老哥，请问你这个有关tp-comm-overlap吗？还是说只要升级了cuda版本就可以了
> 
> 与tp-comm-overlap无关 只需要升级显卡驱动到能支持镜像中的CUDA的版本，就没问题了

请教一下你这个升级驱动版本是与CUDA的版本一致的吗？因为我升级到CUDA Version:12.4 Driver Version:550.54.14之后报了另外一个错误：

![Image](https://github.com/user-attachments/assets/fce3d14b-887e-4518-a854-5117cbda34ef)

**Comment by Lynnzake** [comment]
@yfzhou3993 好的 谢谢
