### ISSUE TITLE
[RuntimeError] 2 * 8 H100 训练deepseek-v2-lite

### ISSUE THREAD

**Issue by cingtiye** [alibaba/Pai-Megatron-Patch#551]
在一台 8*  H100跑deepseek-v2-lite继续预训练正常，切换到两台16 * H100上就出现下面的错误
切分的时候采用默认的PP=4 EP=2 MP_PP0_LAYERS=6
Megatron版本用的默认的：Megatron-LM-241113

RuntimeError: /data1/third_party/TransformerEngine-1.12/transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu:681 in function operator(): cuDNN Error: No valid engine configs for MUL_Reduction_MUL_Matmul_MUL_GEN_INDEX_GEN_INDEX_CMP_GE_BINARY_SELECT_SUB_EXP_Reshape_Matmul_Matmul_MUL_SUB_MUL_MUL_Reshape_Matmul_Reshape_Matmul_IDENTITY_. For more information, enable cuDNN error logging by setting CUDNN_LOGERR_DBG=1 and CUDNN_LOGDEST_DBG=stderr in the environment.

切换了一些tf的版本也不行，希望可以解答一下，非常感谢

**Comment by cingtiye** [comment]
我把FL=false，单机跑会报这个错误，但是设置为true就没有了
多机就不行

**Comment by 154912369** [comment]
+1，deepseekv3在微调某些参数可以，某些参数不可以

**Comment by cingtiye** [comment]
应该是 因为 FUSED_ATTN 不支持 QKV维度不一样

**Comment by cingtiye** [comment]
针对examples/deepseek_v2，这个问题解决了：
在.sh的运行脚本中，选择FL=true表示用FLASH_ATTN

在pretrain_deepseek.py的最前面加上

```python
import os

os.environ['NVTE_FUSED_ATTN'] = "0"
os.environ['NVTE_FLASH_ATTN'] = "1"
```

**Comment by cingtiye** [comment]
> +1，deepseekv3在微调某些参数可以，某些参数不可以

你单独开一个issue吧
